# Copyright 2017 Kamax.io
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

swagger: '2.0'
info:
  title: "Matrix Federation Query Directory API"
  version: "1.0.0"
host: localhost:8448
schemes:
  - https
basePath: /_matrix/federation/v1
produces:
  - application/json
paths:
  "/query/directory":
    get:
      summary: Retrieve the room ID and list of resident homeservers for a room
        alias.
      description: Retrieve the room ID and list of resident homeservers for a Room
        alias.
      parameters:
        - in: query
          name: room_alias
          type: string
          description: Room alias
          required: true
          x-example: "#room_alias:example.org"
      responses:
        200:
          description: The corresponding room ID and list of known resident
            homeservers for the room.
          schema:
            type: object
            properties:
              room_id:
                type: string
                description: The room ID mapped to the queried room alias.
                x-example: "!roomid1234:example.org"
              servers:
                type: array
                description: An array of server names that are likely to hold
                  then given room. This list may or may not include the server
                  answering the query.
                items:
                  type: string
            required:
              - "room_id"
              - "servers"
          examples:
            application/json: {
              "room_id": "!roomid1234:example.org",
              "servers": [
                "example.org",
                "example.com",
                "another.example.com:8449",
              ]
            }